name: Staged Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the code
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  
  prTest:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'pull_request'
    steps:
      - name: Deploy to Dev
        run: echo Deploy to Dev

  deployToDev:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name != 'pull_request'
    steps:
      - name: Deploy to Dev
        run: echo Deploy to Dev

  deployToSbx1:
    runs-on: ubuntu-latest
    environment: sbx1
    needs: [deployToDev]
    steps:
      - name: Deploy to Sbx1
        run: echo Deploy to Sbx1

  deployToQA:
    runs-on: ubuntu-latest
    environment: qa
    needs: [deployToDev]
    steps:
      # Runs a single command using the runners shell
      - name: Deploy to QA
        run: echo Deploy to QA

  deployToStage:
    runs-on: ubuntu-latest
    environment: stage
    needs: [deployToQA]
    steps:
      - name: Deploy to Stage
        run: echo Deploy to Stage

  deployToProd:
    runs-on: ubuntu-latest
    environment: prod
    needs: [deployToQA]
    steps:
      - name: Deploy to Dev
        run: echo Deploy to Prod


